[package]
name = "rustpay"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
ecdsa = { version = "0.16.9", features = ["signing", "verifying"] }
p256 = "0.13.2"
pbkdf2 = "0.12.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
sha2 = "0.10.8"
