#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CountryCode {
    AD,
    AE,
    AL,
    AT,
    AZ,
    BA,
    BE,
    BG,
    BH,
    BR,
    BY,
    CH,
    CY,
    CZ,
    DE,
    DK,
    DO,
    EE,
    ES,
    FI,
    FO,
    FR,
    GB,
    GE,
    GI,
    GL,
    GR,
    GT,
    HR,
    HU,
    IE,
    IL,
    IQ,
    IS,
    IT,
    JO,
    KZ,
    KW,
    LB,
    LC,
    LI,
    LT,
    LU,
    LV,
    MC,
    MD,
    ME,
    MK,
    MR,
    MT,
    MU,
    NL,
    NO,
    PK,
    PL,
    PS,
    PT,
    QA,
    RO,
    RS,
    SA,
    SC,
    SE,
    SI,
    SK,
    SM,
    ST,
    SV,
    TL,
    TN,
    TR,
    UA,
    VA,
    VG,
    XK,
}

impl CountryCode {
    pub fn as_str(&self) -> &str {
        match self {
            CountryCode::AD => "Andorra",
            CountryCode::AE => "United Arab Emirates",
            CountryCode::AL => "Albania",
            CountryCode::AT => "Austria",
            CountryCode::AZ => "Azerbaijan",
            CountryCode::BA => "Bosnia and Herzegovina",
            CountryCode::BE => "Belgium",
            CountryCode::BG => "Bulgaria",
            CountryCode::BH => "Bahrain",
            CountryCode::BR => "Brazil",
            CountryCode::BY => "Belarus",
            CountryCode::CH => "Switzerland",
            CountryCode::CY => "Cyprus",
            CountryCode::CZ => "Czechia",
            CountryCode::DE => "Germany",
            CountryCode::DK => "Denmark",
            CountryCode::DO => "Dominican Republic",
            CountryCode::EE => "Estonia",
            CountryCode::ES => "Spain",
            CountryCode::FI => "Finland",
            CountryCode::FO => "Faroe Islands",
            CountryCode::FR => "France",
            CountryCode::GB => "United Kingdom",
            CountryCode::GE => "Georgia",
            CountryCode::GI => "Gibraltar",
            CountryCode::GL => "Greenland",
            CountryCode::GR => "Greece",
            CountryCode::GT => "Guatemala",
            CountryCode::HR => "Croatia",
            CountryCode::HU => "Hungary",
            CountryCode::IE => "Ireland",
            CountryCode::IL => "Israel",
            CountryCode::IQ => "Iraq",
            CountryCode::IS => "Iceland",
            CountryCode::IT => "Italy",
            CountryCode::JO => "Jordan",
            CountryCode::KZ => "Kazakhstan",
            CountryCode::KW => "Kuwait",
            CountryCode::LB => "Lebanon",
            CountryCode::LC => "Saint Lucia",
            CountryCode::LI => "Liechtenstein",
            CountryCode::LT => "Lithuania",
            CountryCode::LU => "Luxembourg",
            CountryCode::LV => "Latvia",
            CountryCode::MC => "Monaco",
            CountryCode::MD => "Moldova",
            CountryCode::ME => "Montenegro",
            CountryCode::MK => "Macedonia",
            CountryCode::MR => "Mauritania",
            CountryCode::MT => "Malta",
            CountryCode::MU => "Mauritius",
            CountryCode::NL => "Netherlands",
            CountryCode::NO => "Norway",
            CountryCode::PK => "Pakistan",
            CountryCode::PL => "Poland",
            CountryCode::PS => "Palestine",
            CountryCode::PT => "Portugal",
            CountryCode::QA => "Qatar",
            CountryCode::RO => "Romania",
            CountryCode::RS => "Serbia",
            CountryCode::SA => "Saudi Arabia",
            CountryCode::SC => "Seychelles",
            CountryCode::SE => "Sweden",
            CountryCode::SI => "Slovenia",
            CountryCode::SK => "Slovakia",
            CountryCode::SM => "San Marino",
            CountryCode::ST => "Sao Tome and Principe",
            CountryCode::SV => "El Salvador",
            CountryCode::TL => "Timor-Leste",
            CountryCode::TN => "Tunisia",
            CountryCode::TR => "Turkey",
            CountryCode::UA => "Ukraine",
            CountryCode::VA => "Vatican City State",
            CountryCode::VG => "Virgin Islands",
            CountryCode::XK => "Kosovo",
        }
    }

    pub fn as_code(&self) -> (char, char) {
        match self {
            CountryCode::AD => ('A', 'D'),
            CountryCode::AE => ('A', 'E'),
            CountryCode::AL => ('A', 'L'),
            CountryCode::AT => ('A', 'T'),
            CountryCode::AZ => ('A', 'Z'),
            CountryCode::BA => ('B', 'A'),
            CountryCode::BE => ('B', 'E'),
            CountryCode::BG => ('B', 'G'),
            CountryCode::BH => ('B', 'H'),
            CountryCode::BR => ('B', 'R'),
            CountryCode::BY => ('B', 'Y'),
            CountryCode::CH => ('C', 'H'),
            CountryCode::CY => ('C', 'Y'),
            CountryCode::CZ => ('C', 'Z'),
            CountryCode::DE => ('D', 'E'),
            CountryCode::DK => ('D', 'K'),
            CountryCode::DO => ('D', 'O'),
            CountryCode::EE => ('E', 'E'),
            CountryCode::ES => ('E', 'S'),
            CountryCode::FI => ('F', 'I'),
            CountryCode::FO => ('F', 'O'),
            CountryCode::FR => ('F', 'R'),
            CountryCode::GB => ('G', 'B'),
            CountryCode::GE => ('G', 'E'),
            CountryCode::GI => ('G', 'I'),
            CountryCode::GL => ('G', 'L'),
            CountryCode::GR => ('G', 'R'),
            CountryCode::GT => ('G', 'T'),
            CountryCode::HR => ('H', 'R'),
            CountryCode::HU => ('H', 'U'),
            CountryCode::IE => ('I', 'E'),
            CountryCode::IL => ('I', 'L'),
            CountryCode::IQ => ('I', 'Q'),
            CountryCode::IS => ('I', 'S'),
            CountryCode::IT => ('I', 'T'),
            CountryCode::JO => ('J', 'O'),
            CountryCode::KZ => ('K', 'Z'),
            CountryCode::KW => ('K', 'W'),
            CountryCode::LB => ('L', 'B'),
            CountryCode::LC => ('L', 'C'),
            CountryCode::LI => ('L', 'I'),
            CountryCode::LT => ('L', 'T'),
            CountryCode::LU => ('L', 'U'),
            CountryCode::LV => ('L', 'V'),
            CountryCode::MC => ('M', 'C'),
            CountryCode::MD => ('M', 'D'),
            CountryCode::ME => ('M', 'E'),
            CountryCode::MK => ('M', 'K'),
            CountryCode::MR => ('M', 'R'),
            CountryCode::MT => ('M', 'T'),
            CountryCode::MU => ('M', 'U'),
            CountryCode::NL => ('N', 'L'),
            CountryCode::NO => ('N', 'O'),
            CountryCode::PK => ('P', 'K'),
            CountryCode::PL => ('P', 'L'),
            CountryCode::PS => ('P', 'S'),
            CountryCode::PT => ('P', 'T'),
            CountryCode::QA => ('Q', 'A'),
            CountryCode::RO => ('R', 'O'),
            CountryCode::RS => ('R', 'S'),
            CountryCode::SA => ('S', 'A'),
            CountryCode::SC => ('S', 'C'),
            CountryCode::SE => ('S', 'E'),
            CountryCode::SI => ('S', 'I'),
            CountryCode::SK => ('S', 'K'),
            CountryCode::SM => ('S', 'M'),
            CountryCode::ST => ('S', 'T'),
            CountryCode::SV => ('S', 'V'),
            CountryCode::TL => ('T', 'L'),
            CountryCode::TN => ('T', 'N'),
            CountryCode::TR => ('T', 'R'),
            CountryCode::UA => ('U', 'A'),
            CountryCode::VA => ('V', 'A'),
            CountryCode::VG => ('V', 'G'),
            CountryCode::XK => ('X', 'K'),
        }
    }
}